Source/Web/ELearningMathApp.Web/Areas/Ideas/Models/Idea/IdeaViewModel.cs
namespace ELearningMathApp.Web.Areas.Ideas.Models.Idea
{
    using System;
    using System.Collections.Generic;

    using ELearningMathApp.Data.Models;
    using ELearningMathApp.Web.Infrastructure.Mapping;

    public class IdeaViewModel : IMapFrom<IdeaDbModel>
    {
        public int Id { get; set; }

        public string Content { get; set; }

        //public string AuthorId { get; set; }

        public virtual User Author { get; set; }

        public virtual ICollection<User> UsersPozitiveVote { get; set; }

        public virtual ICollection<User> UsersNegativeVote { get; set; }

        public DateTime CreatedOn { get; set; }
    }
}

Source/Web/ELearningMathApp.Web/Areas/Ideas/Controllers/IdeaController.cs
using ELearningMathApp.Data.Common.Repository;
using ELearningMathApp.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

using AutoMapper.QueryableExtensions;
using ELearningMathApp.Web.Areas.Ideas.Models.Idea;

namespace ELearningMathApp.Web.Areas.Ideas.Controllers
{
    public class IdeaController : Controller
    {
        private IRepository<IdeaDbModel> ideasRepo;

        public IdeaController(IRepository<IdeaDbModel> ideasRepo)
        {
            this.ideasRepo = ideasRepo;
        }

        // GET: Ideas/Idea
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult CreateIdea(string idea)
        {
            if (idea != null && idea.Length > 50)
            {
                // save to db
                var newIdea = new IdeaDbModel()
                    {
                        AuthorId = this.User.Identity.GetUserId(),
                        Content = idea,
                        CreatedOn = DateTime.Now
                    };

                this.ideasRepo.Add(newIdea);
                this.ideasRepo.SaveChanges();

                return RedirectToAction("ShowIdeas");
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ShowIdeas()
        {
            var ideas = this.ideasRepo
                .All()
                .OrderBy(i => i.CreatedOn)
                .Project()
                .To<IdeaViewModel>()
                .ToList();

            return View(ideas);
        }
    }
}

Source/Web/ELearningMathApp.Web/Areas/Ideas/Views/Idea/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Write your idea</h2>
<div>
    @using (@Html.BeginForm("CreateIdea", "Idea", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <br />
        <div class="container">
            <div class="row">
                <div class="col-md-10">
                    @Html.Label("", "Public your idea:")
                    @Html.TextArea("idea", "", new { @class = "form-control", @placeholder = "Share your idea hire:", @type = "text", TextMode = "MultiLine" })
                </div>
            </div>
        </div>
        <br />
        <input type="submit" name="Send" value="Send" class="btn btn-primary" />
    }
</div>

Source/Web/ELearningMathApp.Web/Areas/Ideas/Views/Idea/ShowIdeas.cshtml
@model ICollection<ELearningMathApp.Web.Areas.Ideas.Models.Idea.IdeaViewModel>
@{
    ViewBag.Title = "All Ideas";
}

<h2>Ideas</h2>
<br />
<div class="container">
    @foreach (var idea in Model)
    {
        <div class="row">
            <div class="col-md-3">
                <div class="row">
                    <div class="col-md-2">
                        <a href="#" class="btn btn-sm btn-default">^</a>
                        <br />
                        <a href="#" class="btn btn-sm btn-default">v</a>
                    </div>
                    <div class="col-md-10">
                        <h3>@(idea.UsersPozitiveVote.Count - idea.UsersNegativeVote.Count) votes</h3>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="row">
                    <p>@idea.Content</p>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <p>Author: @idea.Author.UserName</p>
                    </div>
                    <div class="col-md-6">
                        <p>Date: @idea.CreatedOn.ToUniversalTime()</p>
                    </div>
                </div>
            </div>
        </div>
        <hr />
    }
</div>